name: cicd pipeline
on: push

jobs:
    build-job:
      runs-on: ubuntu-latest
      steps:
        - name: cat command
          run: cat /etc/passwd
    test-job:
        needs: build-job
        runs-on: ubuntu-latest
        steps:
        - name: list files
          run: |
            ls
            date
            pwd

